<ADSWorkspace Revision="6" Version="100">
    <Workspace Name="">
        <LibraryDefs Name="lib.defs" />
        <ConfigFile Name="dds.cfg" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Data_Display Name="Ideal TRLs.dds" />
        <Log Name="netlist.log" />
        <Log Name="search_history.log" />
        <Preferences Name="ads_datacmps_lay.prf" />
        <Preferences Name="EE 456 Design 1_lib_lay.prf" />
        <Preferences Name="layout.prf" />
        <Preferences Name="schematic.prf" />
        <Dataset Name="Ideal_TRLs.ds" />
        <Data_Files Name="EE 456 Design Project 1 SPout.s2p" />
        <Data_Files Name="Ideal_TRLs.ds" />
        <Data_Files Name="Ideal_TRLs_data\logFile.txt" />
        <Library Name="ads_standard_layers_ic" />
        <Library Name="ads_schematic_layers_ic" />
        <Library Name="ads_schematic_ports_ic" />
        <Library Name="ads_sources" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_pelib" />
        <Library Name="ads_serdes_ref_channel" />
        <Library Name="ads_quantum" />
        <Library Name="ads_standard_layers" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_builtin" />
        <Library Name="ads_rflib" />
        <Library Name="ads_simulation" />
        <Library Name="ads_datacmps" />
        <Library Name="Simulation_Sequencing" />
        <Library Name="EE 456 Design 1_lib" />
        <Cell Name="EE 456 Design 1_lib:Ideal TRLs IMN" />
        <Cell Name="EE 456 Design 1_lib:Ideal TRLs OMN" />
        <Dataset Name="Ideal_TRLs_IMN.ds" />
        <Data_Files Name="EE 456 Design Project 1 SPout IMN.s2p" />
        <Data_Files Name="Ideal_TRLs_IMN.ds" />
        <Data_Files Name="Ideal_TRLs_IMN_data\logFile.txt" />
        <Data_Display Name="Ideal TRLs IMN.dds" />
        <Dataset Name="Ideal_TRLs_OMN.ds" />
        <Data_Files Name="EE 456 Design Project 1 SPout OMN.s2p" />
        <Data_Files Name="Ideal_TRLs_OMN.ds" />
        <Data_Files Name="Ideal_TRLs_OMN_data\logFile.txt" />
        <Data_Display Name="Ideal TRLs OMN.dds" />
        <Cell Name="EE 456 Design 1_lib:Ideal TRLs In" />
        <Cell Name="EE 456 Design 1_lib:Ideal TRLs Out" />
        <Dataset Name="Ideal_TRLs_In.ds" />
        <Data_Files Name="EE 456 Design Project 1 SPout In.s2p" />
        <Data_Files Name="Ideal_TRLs_In.ds" />
        <Data_Files Name="Ideal_TRLs_In_data\logFile.txt" />
        <Data_Display Name="Ideal TRLs In.dds" />
        <Dataset Name="Ideal_TRLs_Out.ds" />
        <Data_Files Name="EE 456 Design Project 1 SPout Out.s2p" />
        <Data_Files Name="Ideal_TRLs_Out.ds" />
        <Data_Files Name="Ideal_TRLs_Out_data\logFile.txt" />
        <Data_Display Name="Ideal TRLs Out.dds" />
        <Cell Name="EE 456 Design 1_lib:Ideal TRLs DC" />
        <Data_Display Name="Ideal TRLs DC.dds" />
        <Dataset Name="Ideal_TRLs_DC.ds" />
        <Data_Files Name="EE 456 Design Project 2 SPout DC.s2p" />
        <Data_Files Name="EE 456 Design Project 2 SPout IMN.s2p" />
        <Data_Files Name="EE 456 Design Project 2 SPout In.s2p" />
        <Data_Files Name="EE 456 Design Project 2 SPout OMN.s2p" />
        <Data_Files Name="EE 456 Design Project 2 SPout Out.s2p" />
        <Data_Files Name="Ideal_TRLs_DC.ds" />
        <Data_Files Name="Ideal_TRLs_DC_data\logFile.txt" />
        <Library Name="1xEV" />
        <Library Name="3GPPFDD" />
        <Library Name="3GPPFDD_10_99" />
        <Library Name="Antennas_and_Propagation" />
        <Library Name="CDMA" />
        <Library Name="cdma2000" />
        <Library Name="Circuit_Cosimulation" />
        <Library Name="CMMB" />
        <Library Name="Controllers" />
        <Library Name="DTMB" />
        <Library Name="DTV" />
        <Library Name="EDGE" />
        <Library Name="GSM" />
        <Library Name="HDL_Blocks" />
        <Library Name="HSDPA" />
        <Library Name="HSUPA" />
        <Library Name="Instruments" />
        <Library Name="Interactive_Controls_and_Displays" />
        <Library Name="LTE" />
        <Library Name="Numeric" />
        <Library Name="Obsolete" />
        <Library Name="Signal_Converters" />
        <Library Name="Sinks" />
        <Library Name="SystemVue_Cosimulation" />
        <Library Name="TDSCDMA" />
        <Library Name="Timed" />
        <Library Name="UMB" />
        <Library Name="UWB" />
        <Library Name="WLAN" />
        <Library Name="WLAN_11n" />
        <Library Name="WMAN" />
        <Library Name="WMAN_16e" />
    </Workspace>
</ADSWorkspace>
